# Setup
title:            Nikhil Daga
tagline:          '- Entrepreneur, Developer, Astrologer'
email:            nikhil.daga.bitsian@gmail.com
description:      'Nikhil Daga -  Entrepreneur, Developer, Astrologer'
url:              "http://nikhilda.ga"
baseurl:          ""
author:
  name:           'Nikhil Daga'
  url:            "https://google.com/+nikhildaga"
paginate:         5
sitemap:
  priority: 0.7
  changefreq: daily

# Custom vars
version:          1.0.0

# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
